### ISSUE TITLE
Have you checked to see if there are 8 scenes, not 4?

### ISSUE THREAD

**Issue by BrianAker** [michaelphilip/SmartThings#4]
The VRCS4-M0Z supports 8 scenes ( groups associated with scenes) in total.  Four for each buttons on/off.
I don't have a VRCZ4, but the other models of scene controllers have a number of group/scene which are multiple of 2 for the number of buttons on the controller ( minus dimming). 
You may have to set a value for the sceneID in order to get a report from groups 5-8.

**Comment by michaelphilip** [comment]
Well...this is for the VRCZ4-M0Z, but yes -- it uses 8 scenes (on/off for each of four groups)
