### ISSUE TITLE
SceneActuatorConfGet() needs to be followed up by SceneActuatorConfReport()

### ISSUE THREAD

**Issue by BrianAker** [michaelphilip/SmartThings#5]
Since ST doesn't do any of the heavy lifting for scenes, a driver needs to handle the response for SceneActuatorConfGet(), which is SceneActuatorConfReport().
The switch is asking via SceneActuatorConfGet() about the state following an activation of a scene. The scene controller will, under certain firmware, timeout if it never gets a response ( though eventually many of these scene controller will get hung up and require cutting power to the circuit in order to get them to work again ).

**Comment by michaelphilip** [comment]
Are you running into trouble with the SmartApp/DTH for the VRCZ4-M0Z?  I have four of them running here -- all working fine
